Repository XyrisOS/xyris, pull requests merged in 2020-10, with the labels that each got.

#129 Added Stack Trace Memcheck
  kernel/mem/paging.cpp
  kernel/sys/trace.cpp
  sysroot/usr/include/kernel/lib/bitmap.hpp
  sysroot/usr/include/kernel/mem/paging.hpp
Labels: enhancement

#131 Change Compiler to Clang++
  Makefile
  kernel/dev/rtc/rtc.cpp
  kernel/dev/serial/rs232.cpp
  kernel/lib/string.cpp
  kernel/sys/panic.cpp
  sysroot/usr/include/kernel/dev/serial/rs232.hpp
  sysroot/usr/include/kernel/sys/panic.hpp
Labels: enhancement

#135 Add Debug Build Target
  .vscode/c_cpp_properties.json
  Makefile
  kernel/lib/debug.cpp
  kernel/mem/heap.cpp
  kernel/mem/paging.cpp
  sysroot/usr/include/kernel/lib/stdio.hpp
Labels: hacktoberfest-accepted

#120 Kernel Tasks
  Makefile
  kernel/arch/i386/tasks.S
  kernel/arch/i386/timer.cpp
  kernel/mem/paging.cpp
  kernel/sys/tasks.cpp
  sysroot/usr/include/kernel/arch/i386/timer.hpp
  sysroot/usr/include/kernel/mem/paging.hpp
  sysroot/usr/include/kernel/sys/tasks.hpp
Labels: in-progress

#143 Makefile Fix to Append Environment Variables
  Makefile
Labels: bug
